### ISSUE TITLE
$date->is_date(1) converts empty input to 0001-01-01

### ISSUE THREAD

**Issue by ehuelsmann** [pgobject/PGObject-Type-DateTime#1]
@einhverfr when setting is_date(), a null input ('') is converted to 0001-01-01.

Wondering if that's the right thing to do. It broke up LedgerSMB (although LSMB works around it now.)

**Comment by einhverfr** [comment]
The problem here currently is I couldnt find a good way to set a valid datetime value from this and since we inherit, there is no real null handling.

I am not sure of the correct approach here.  Thoughts are welcome.

**Comment by einhverfr** [comment]
So as I am thinking about this, the problem is an LSP violation.  There is not a clean way to do this. 

The problem is really with DateTime rather than on our side.  So the question is what we want to do about it.  Maybe we should use an inner object and wrappers like we did before?

**Comment by einhverfr** [comment]
This actually is worse than I thought, playing around with it.   Year is a required parameter.  However, all other parameters are set to their defaults.  So DateTime is inconsistent on this point.  I think this is the best we can do with this for now unless we want to write a better module.
