### ISSUE TITLE
Need to use PGObject before consulting its $VERSION ?

### ISSUE THREAD

**Issue by ehuelsmann** [pgobject/PGObject-Type-DateTime#12]
@einhverfr Possibly, this doesn't work:

https://github.com/ledgersmb/PGObject-Type-DateTime/blob/349454a2ba94a61c541b674428b137cc91158bc4/lib/PGObject/Type/DateTime.pm#L77

because we never used or required PGObject?

**Comment by einhverfr** [comment]
Reviewing the code, there is a decision we should make here.  In general I think doing the use statement is a good idea.  But registering the module makes no sense unless PGObject is already loaded.  There is nothing outside of registration which uses PGObject.  So are there any use cases where we want to use this unregistered and independent?

**Comment by ehuelsmann** [comment]
While it doesn't make sense to use one without the other, what guarantees
that the correct load-order is being respected if we don't force the
correct load order? E.g. one could use this module in their code before
using PGObject (either explicitly or accidentally).

**Comment by ehuelsmann** [comment]
I found the cause for the use of the wrong `if` branch while running PGObject 2.0.1, btw, to be an incorrect regex. Releasing version 2.0.1 with the corrected regex which means we won't see any further warnings about using the deprecated interface when using PGObject 2+.

So, my initial hypothesis that the value of PGObject::VERSION isn't defined and that that causes the wrong branch to be executed, is hereby invalidated.
