### ISSUE TITLE
Forward compatability: Passing arbitrary arguments to the constructor fails hard

### ISSUE THREAD

**Issue by ehuelsmann** [pgobject/PGObject-Type-DateTime#5]
Well, this is more of an issue with DateTime, with which we share our constructor, but arguments meaningful to a derived class can't be passed on to our constructor, because the one we inherited will fail hard with unsuported arguments.

While we can filter for allowed arguments, that's hardly forward-compatible, because DateTime might start to support new ones in a later release and people may want to use those with our class.

**Comment by einhverfr** [comment]
I am wondering if a lot of our problems are effectively the choice of inheriting from DateTime.  If we want to filter, we could specify a series of our own parameters rather than simple handling unknown ones as such.

**Comment by einhverfr** [comment]
I think for now, we should close this and assume that this is the responsibility of subclasses.

However one thing these issues have suggested to me is that Perl's DateTime library is not really very good at handling the various things we serialize from the database.  We probably want to create our own library for that in the future if we don't find another.  This library takes things out as a DateTime type.  I think we should expect that by 3.0 this library should remove handling of times of days and come up with some other null handling (perhaps wrap some other methods).  Throughout 2.x we should be able to better handle NULLs
